// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3z-GPbfD_xs1YI6oMLtv1E_PHxR9ah34',
    appId: '1:622698480676:web:f6733380affffc4f8384b1',
    messagingSenderId: '622698480676',
    projectId: 'my-project-6c540',
    authDomain: 'my-project-6c540.firebaseapp.com',
    storageBucket: 'my-project-6c540.appspot.com',
    measurementId: 'G-Z52689476L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2qn6OUO96M2hlwNkdAOnUIIFuOOzHWwQ',
    appId: '1:622698480676:android:7731acf4aa9bd2858384b1',
    messagingSenderId: '622698480676',
    projectId: 'my-project-6c540',
    storageBucket: 'my-project-6c540.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClRuHqPS3DROHeGtHzUqOx_Be5hx5BVaw',
    appId: '1:622698480676:ios:f61004ec51965a378384b1',
    messagingSenderId: '622698480676',
    projectId: 'my-project-6c540',
    storageBucket: 'my-project-6c540.appspot.com',
    iosClientId: '622698480676-scqq5cjjjl2ud118okq6ih3l05pouvkp.apps.googleusercontent.com',
    iosBundleId: 'com.example.noteApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClRuHqPS3DROHeGtHzUqOx_Be5hx5BVaw',
    appId: '1:622698480676:ios:f61004ec51965a378384b1',
    messagingSenderId: '622698480676',
    projectId: 'my-project-6c540',
    storageBucket: 'my-project-6c540.appspot.com',
    iosClientId: '622698480676-scqq5cjjjl2ud118okq6ih3l05pouvkp.apps.googleusercontent.com',
    iosBundleId: 'com.example.noteApp',
  );
}
